name: portofalio
description: "Thabit Budeir — Personal Digital Identity"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  http: ^1.6.0
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/projects/
    - assets/certificates/
    - assets/designs/
    - assets/designs/AURIX/
    - assets/designs/NABDH/
    - assets/designs/Fodoora/
    - "assets/designs/Dashboard UI/"
    - assets/profile/
    - assets/signature/
    - assets/my_visual_identy/
    - assets/Thabit_Budeir_CV.pdf
